### ISSUE TITLE
Plural not match for some words

### ISSUE THREAD

**Issue by bxliu** [yanndemel/crud-rest-gen#1]
ADocEntityGenerator.getPluralName not match the plural method spring rest using.

for example ****Info->****Infoes

can change to org.atteo.evo-inflector

		<dependency>
			<groupId>org.atteo</groupId>
			<artifactId>evo-inflector</artifactId>
			<version>${evoinflector}</version>
		</dependency>

**Comment by yanndemel** [comment]
Thanks for the suggestion -> getPluralName methods have been changed (+pom versions : 0.0.2-SNAPSHOT) : use of evo-inflector (English.plural)
