### ISSUE TITLE
pluralName for template should uncapitalized

### ISSUE THREAD

**Issue by bxliu** [yanndemel/crud-rest-gen#3]
entityInfo.put("pluralName", StringUtils.plural(name.substring(0, 1).toLowerCase() + name.substring(1)));

all path in spring data rest is uncapitalized.
StringUtils.uncapitalize(type.getSimpleName());

**Comment by yanndemel** [comment]
Corrected [here](https://github.com/yanndemel/crud-rest-gen/commit/17517609dbef67856e05b9de0499f2f503731b72)
