### ISSUE TITLE
plural method is not match java code in javascript

### ISSUE THREAD

**Issue by bxliu** [yanndemel/crud-rest-gen#4]
as title.

**Comment by yanndemel** [comment]
Issue corrected (see [commit](https://github.com/yanndemel/crud-rest-gen/commit/17517609dbef67856e05b9de0499f2f503731b72))

Thanks!

**Comment by bxliu** [comment]
what i mean is that:

`var plural = function(name) {
	if(name == null || name == "") {
		return name;
	}
	var entities1 = name.endsWith("y") ? name.substring(0, name.length - 1) + "ies"
			: name.endsWith("s") ? name + "es" : name + "s";
	return uncapitalize(entities1);
}`

**Comment by bxliu** [comment]
maybe some js library like https://github.com/blakeembrey/pluralize

**Comment by yanndemel** [comment]
Thx, I have already included it in last [commit ](https://github.com/yanndemel/crud-rest-gen/commit/a8173a2c0ce0044a4b2139623067f6e7ec1e0f94)
