### ISSUE TITLE
Rest doc forget page links

### ISSUE THREAD

**Issue by bxliu** [yanndemel/crud-rest-gen#5]
Rest doc forget page links, if 20 more records in existing dataset, test will fail.

should add following code to EntitiesApiDocumentation.getLinksForList

`		if (info.isPaged()) {
			list.add(linkWithRel("first").optional().description("The first page of results"));
			list.add(linkWithRel("last").optional().description("The last page of results"));
			list.add(linkWithRel("next").optional().description("The next page of results"));
			list.add(linkWithRel("prev").optional().description("The previous page of results"));
		}`

**Comment by yanndemel** [comment]
[Corrected](https://github.com/yanndemel/crud-rest-gen/commit/51881c549b84d866165bd3f952c72a7beb915d6b). Thx bxliu - don't hesitate to make pull requests ;-)
